apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: isf-catalog
  namespace: openshift-marketplace
spec:
  displayName: ISF Catalog
  image: <catalogsource>
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 1m
